# Build backend/.env.railway from .env.railway-restore (DB) + .env (JWT).
$ErrorActionPreference = 'Stop'
$projectRoot = Resolve-Path (Join-Path $PSScriptRoot '..')
$restoreFile = Join-Path $projectRoot 'backend\.env.railway-restore'
$localFile = Join-Path $projectRoot 'backend\.env'
$outFile = Join-Path $projectRoot 'backend\.env.railway'

if (-not (Test-Path -LiteralPath $restoreFile)) {
  Write-Error 'Missing backend/.env.railway-restore. Copy backend/.env.railway-restore.example and fill Railway MySQL public proxy credentials.'
}

function Read-EnvMap {
  param([Parameter(Mandatory = $true)][string]$Path)

  $map = @{}
  foreach ($rawLine in Get-Content -LiteralPath $Path) {
    $line = $rawLine.Trim()
    if ($line -eq '' -or $line.StartsWith('#')) { continue }
    $eq = $line.IndexOf('=')
    if ($eq -lt 1) { continue }
    $key = $line.Substring(0, $eq).Trim().TrimStart([char]0xFEFF)
    $map[$key] = $line.Substring($eq + 1).Trim()
  }
  return $map
}

$restore = Read-EnvMap -Path $restoreFile
$local = if (Test-Path -LiteralPath $localFile) { Read-EnvMap -Path $localFile } else { @{} }

$requiredRestore = @('DB_HOST', 'DB_PORT', 'MASTER_DB_USER', 'MASTER_DB_PASSWORD')
foreach ($key in $requiredRestore) {
  if (-not $restore.ContainsKey($key) -or [string]::IsNullOrWhiteSpace($restore[$key])) {
    Write-Error "Missing or empty $key in backend/.env.railway-restore. Copy backend/.env.railway-restore.example and fill Railway MySQL Connect -> Public network values."
  }
}

$jwt = $local['JWT_SECRET']
if ([string]::IsNullOrWhiteSpace($jwt)) {
  Write-Error 'JWT_SECRET not found in backend/.env. Add it or set manually in backend/.env.railway.'
}

$content = @(
  '# Auto-generated by scripts/setup-env-railway.ps1 - local dev against Railway production DB'
  "DB_HOST=$($restore['DB_HOST'])"
  "DB_PORT=$($restore['DB_PORT'])"
  'DB_DATABASE=budgeteer'
  "MASTER_DB_USER=$($restore['MASTER_DB_USER'])"
  "MASTER_DB_PASSWORD=$($restore['MASTER_DB_PASSWORD'])"
  'DB_SSL=false'
  "JWT_SECRET=$jwt"
  'PORT=3000'
  'PRODUCTION=false'
)

Set-Content -LiteralPath $outFile -Value $content -Encoding utf8
Write-Host "Wrote $outFile"
