# Build backend/.env.railway from .env.railway-restore (DB) + .env (JWT).
$ErrorActionPreference = 'Stop'
$backend = Join-Path $PSScriptRoot '..\backend'
$restoreFile = Join-Path $backend '.env.railway-restore'
$localFile = Join-Path $backend '.env'
$outFile = Join-Path $backend '.env.railway'

if (-not (Test-Path $restoreFile)) {
  Write-Error "Missing $restoreFile — copy backend/.env.railway-restore.example and fill Railway MySQL public proxy creds."
}

function Read-EnvFile($path) {
  $vars = @{}
  Get-Content $path | ForEach-Object {
    $line = $_.Trim()
    if ($line -eq '' -or $line.StartsWith('#')) { return }
    $eq = $line.IndexOf('=')
    if ($eq -lt 1) { return }
    $vars[$line.Substring(0, $eq).Trim()] = $line.Substring($eq + 1).Trim()
  }
  return $vars
}

$restore = Read-EnvFile $restoreFile
$local = if (Test-Path $localFile) { Read-EnvFile $localFile } else { @{} }

$jwt = $local['JWT_SECRET']
if (-not $jwt) {
  Write-Error "JWT_SECRET not found in backend/.env — add it or set manually in .env.railway."
}

$content = @"
# Auto-generated by scripts/setup-env-railway.ps1 — local dev against Railway production DB
DB_HOST=$($restore['DB_HOST'])
DB_PORT=$($restore['DB_PORT'])
DB_DATABASE=budgeteer
MASTER_DB_USER=$($restore['MASTER_DB_USER'])
MASTER_DB_PASSWORD=$($restore['MASTER_DB_PASSWORD'])
DB_SSL=false
JWT_SECRET=$jwt
PORT=3000
PRODUCTION=false
"@

Set-Content -Path $outFile -Value $content.TrimEnd() -Encoding utf8
Write-Host "Wrote $outFile"
